qaprosoft/react-laba-arg-1

homeworks/nicolas-roberto/04-css/index.html, homeworks/nicolas-roberto/05-css/css/styles.css, homeworks/nicolas-roberto/05-css/index.html
Resized "Software engineer" text in dark mode. Also corrected some grammatical mistakes.
=> [homework #5] - CSS Advanced by Nicolás Roberto

homeworks/edelmiro-anton/06-JS-basics/basics_1.js
Hey! @ilya-ischenko
Here are the katas that Mike told us to push so you can take a look. 
Meanwhile I'll continue with the rest and the next hw.
Thanks!
=> [homework #6] - js basics 1 by Edelmiro Antón

homeworks/julian-oviedo/06-js-basics-1, homeworks/julian-oviedo/06-js-basics-1/script.js
Hi @ilya-ischenko, I couldn't do katas numbers 5 and 16 but, as Misha said, i do the PR anyway.
=> [homework #6] - JS by Julian Oviedo

homeworks/edelmiro-anton/07-js-basics/basics_2.js
Hey @ilya-ischenko. Here's my hw #7.
Let me know if there's somewthing to fix.  Thanks you!
=> [homework #7] - js-basics-2 by Edelmiro Anton

homeworks/emiliano-acerbi/07-js-basics-2/index.js
Hello @VitalikMelnyk . This is my submission for the 7th lecture. Please let me know if there's anything to fix.
=> [homework #7] - js-basics-2 by Emiliano Acerbi

homeworks/emiliano-acerbi/08-js-advanced-1/index.js
Hello @VitalikMelnyk . This is my submission for the 8th lecture. Please let me know if there's anything I should fix.
Talk to you soon
=> [homework #8] - js-advanced-1 by Emiliano Acerbi

homeworks/emiliano-acerbi/10-js-dom/index.html, homeworks/emiliano-acerbi/10-js-dom/index.js, homeworks/emiliano-acerbi/10-js-dom/style.css
Hi @VitalikMelnyk ! This is my first iteration of the 10th task. Please let me know if there's anything to fix.
=> [homework #10] - js-dom by Emiliano Acerbi

homeworks/emiliano-acerbi/11-js-advanced-3/Codewars/index.js, homeworks/emiliano-acerbi/11-js-advanced-3/Fetch Task/index.html, homeworks/emiliano-acerbi/11-js-advanced-3/Fetch Task/index.js, homeworks/emiliano-acerbi/11-js-advanced-3/Fetch Task/style.css, homeworks/emiliano-acerbi/11-js-advanced-3/Interval Task/index.js, homeworks/emiliano-acerbi/11-js-advanced-3/Regex Tasks/index.js
Hi @VitalikMelnyk. Please let me know if there's anything to fix.
Talk to you soon
=> [homework #11] - js-advanced-3 by Emiliano Acerbi

homeworks/edelmiro-anton/08-js-advanced-1/advanced-1.js
Hey @ilya-ischenko!
Here's my hw. I'm finishing the other tasks. 
Please let me know if I have to do some modifications.
Thanks!
=> [homework #8] - js-advanced-1 by Edelmiro Anton

homeworks/candelaria-barcelo/08-js-advanced-1/index.js
Hello @VitalikMelnyk ! I am submitting homework 8 + one of the optional tasks. I'm having a little trouble with task number 6, if you could guide me a little I would appreciate it very much. 
Thank you!
=> [homework #8] - js-advanced-1 by Candelaria Barcelo

homeworks/candelaria-barcelo/10-js-dom/index.css, homeworks/candelaria-barcelo/10-js-dom/index.html, homeworks/candelaria-barcelo/10-js-dom/index.js
Hello @VitalikMelnyk , I've finished homework 10 + the optional advanced task.
Thank you in advance for your review.
=> [homework #10] - js-dom by Candelaria Barcelo

homeworks/emiliano-acerbi/09-js-advanced-2/index.js
Hello @VitalikMelnyk . This is my first iteration of the 9th lecture. I'm having trouble in line 73 when I try to format the date, but all the other tests are passing.
Please let me know if there's anything to fix.
=> [homework #9] - js-advanced-2 by Emiliano Acerbi

homeworks/brisa-rojas/11-js-advanced-3/XMLHttpRequest.js, homeworks/brisa-rojas/11-js-advanced-3/fetch.js, homeworks/brisa-rojas/11-js-advanced-3/index.html, homeworks/brisa-rojas/11-js-advanced-3/styles.css, homeworks/brisa-rojas/11-js-advanced-3/task11.js
Hi Ilya, here's my homework 10
Let me know if I need to change anything
Thanks in advance
=> [homework #11] - js-advanced-3 by Brisa Rojas

homeworks/nicolas-roberto/07-js/main.js
Still working on the rest of the katas.
=> [homework #7] - js basics 2 by Nicolás Roberto

homeworks/brisa-rojas/09-js-advanced-2/serializable.js
Hi @ilya-ischenko, here's my hw 9.
Let me know if theres's something to change!
=>  [homework #9] - js-advanced-2 by Brisa Rojas

homeworks/edelmiro-anton/11-js-advanced-3/index.html, homeworks/edelmiro-anton/11-js-advanced-3/indexXML.html, homeworks/edelmiro-anton/11-js-advanced-3/script.js, homeworks/edelmiro-anton/11-js-advanced-3/styles.css, homeworks/edelmiro-anton/11-js-advanced-3/xml.js
Hi @ilya-ischenko!
Here's my submission of the hw #11. Let me know if you have some comments. 
Thanks in advance!
=> [homework #11] - js-advanced-3 by Edelmiro Anton

homeworks/edelmiro-anton/10-js-dom/index.html, homeworks/edelmiro-anton/10-js-dom/script.js, homeworks/edelmiro-anton/10-js-dom/styles.css
Hey @ilya-ischenko!
Here's my hw 10. Please let me know if I have to fix something.
Thanks!
=> [homework #10] - js-dom by Edelmiro Anton

homeworks/david-azuaje/08-js-advanced-1/script.js
Hi Mike!
Let me know If I should fix something
=> [homework #8] - js-advanced-1 by David Azuaje

homeworks/david-azuaje/10-js-dom/index.html, homeworks/david-azuaje/10-js-dom/script.js, homeworks/david-azuaje/10-js-dom/style.css
Hi Mike!
Let me know if I should fix something in the code.
=> [homework #10] - Js-DOM by David Azuaje

homeworks/federico-benitez/09-js-advanced-2/index.js
Hi @VitalikMelnyk, here is my task. 
Let me know if I should change anything
=> [homework #9] - Js advanced 2 by Federico Benitez

homeworks/edelmiro-anton/09-js-advanced-2/script.js
Hi @ilya-ischenko! Here's my submition of the hw 9.
I'll look forward for your comments.
Thanks!
=> [homework #9] - js-advanced-2 by Edelmiro Anton

homeworks/julian-oviedo/09-js-advanced-2/main.js
Hi @ilya-ischenko ! Here is my task #9. Take a look please and let me know if i need to change or just improve anything.
Thank You !!!
=> [homework #9] - js-advanced-2 by Julian Oviedo

homeworks/abraham-trenyan/10-js-dom/index.html, homeworks/abraham-trenyan/10-js-dom/script.js, homeworks/abraham-trenyan/10-js-dom/styles.css
Hey Vitali, I haven't finished with this one, but I created PR so you can see how I'm doing anyways.
My main issue is that I can't handle disallowing multiple selections of cells.
I'm going to try to solve this on the weekend, but this is my progress till now.
=> [homework #10] - Js-DOM by Abraham Trenyan

homeworks/emiliano-acerbi/16-react-basics/index.html, homeworks/emiliano-acerbi/16-react-basics/index.js, homeworks/emiliano-acerbi/16-react-basics/style.css
Hello @VitalikMelnyk! This is my submission for the traffic light exercise. Please let me know if there's anything to fix.
Thank you
=> [homework #16] - react-basics by Emiliano Acerbi

homeworks/german-macchia/16-react-basics/index.html, homeworks/german-macchia/16-react-basics/script.js, homeworks/german-macchia/16-react-basics/style.css, package-lock.json
Hey @VitalikMelnyk !
Here is my react homework! 
I will try to work on the second part to see how if I can measure the reconciliation, but i'm still not pretty sure how can i do it.
May be I will ask on slack to everyone, If someone could figure out!
Cheers!
=> [homework #16] - react-basics by German Macchia

homeworks/nicolas-roberto/16-react-basics/index.html, homeworks/nicolas-roberto/16-react-basics/main.js, homeworks/nicolas-roberto/16-react-basics/styles.css
Hey Misha, good morning. I finished my homework. Let me know if there's something to improve/fix.
=> [Homework #16] - React-basics by Nicolás Roberto

homeworks/abraham-trenyan/16-react-basics/index.html, homeworks/abraham-trenyan/16-react-basics/script.js, homeworks/abraham-trenyan/16-react-basics/styles.css
Hi Vitali, let's talk if there's something to improve on this homework!
=> [Homework #16] - react-basics by Abraham Trenyan

homeworks/edelmiro-anton/16-react-basics/index.html, homeworks/edelmiro-anton/16-react-basics/index.js, homeworks/edelmiro-anton/16-react-basics/styles.css
Hi @ilya-ischenko!
Here's my hw. Let me know if I have to fix something from the code.
Thanks in advance!
=> [Homework #16] - React-basics by Edelmiro Antón

homeworks/julian-oviedo/16-react-basics/app.js, homeworks/julian-oviedo/16-react-basics/index.html, homeworks/julian-oviedo/16-react-basics/styles.css
Hi Ilya ! This is my hw, please, let me know if i need to improve something.
Thank you !
=> [Homework #16] - React Basics by Julian Oviedo

homeworks/david-azuaje/16-react-basics/index.html, homeworks/david-azuaje/16-react-basics/script.js, homeworks/david-azuaje/16-react-basics/style.css
Hey Mike!
Here is the submission of homework 16#, let me know if it's OK.
=> [Homework #16] - React Basics by David Azuaje
